# Generated by Django 2.1.7 on 2019-04-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media/images/<function generate_filename at 0x03498348>'),
        ),
    ]
