# Generated by Django 2.1.7 on 2019-05-10 19:03

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190510_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.generate_filename),
        ),
    ]
